/**
 * @file VOXELIA world worker entry point (ARCHITECTURE.md 5.15).
 *
 * A module worker (`new Worker(url, { type: 'module' })`) that owns one
 * {@link WorldGenerator} and one mesher scratch set for its whole lifetime, so
 * neither terrain generation nor meshing ever blocks the render thread.
 *
 * ## Protocol
 *
 * | inbound | outbound |
 * |---|---|
 * | `{type:'init', id?, seed, options}` | `{type:'ready', id, seed, genVersion, vertexStride, blocks, structures}` |
 * | `{type:'gen', id, cx, cz}` | `{type:'gen', id, cx, cz, sections, heightmap, biomes, oceanFloor, edits}` |
 * | `{type:'mesh', id, cx, cz, sy, blocks, light, biomes, smoothLighting, fancyLeaves}` | `{type:'mesh', id, cx, cz, sy, opaque, cutout, water}` |
 * | `{type:'dispose'}` | — (the worker closes itself) |
 *
 * Every `ArrayBuffer` in a reply is transferred, never copied; the transfer
 * list is de-duplicated so generators that carve their sections out of one
 * shared buffer cannot trigger a double-transfer `DataCloneError`.
 *
 * Deferred structure edits (`WorldGenerator.takePendingEdits()`) travel back as
 * `[chunkKey, Int32Array]` pairs of flat `x, y, z, blockId` quadruplets; the
 * main thread stores them until the target chunk exists.
 *
 * Nothing here ever throws out of the message handler: every failure is
 * reported as `{type:'error', id, message, stack}` so the pool keeps running.
 */

import { WorldGenerator, GEN_VERSION } from './worldgen.js';
import { STRUCTURES } from './structures.js';
import { meshSectionInto, createMeshScratch, VERTEX_STRIDE } from './mesher.js';
import { BLOCK_BY_NAME, BLOCK_COUNT } from './blocks.js';
import { resolveBiomeBlocks } from './biomes.js';

/** Sections per chunk column (spec 2). @type {number} */
const SECTION_COUNT = 24;
/** Voxels per section. @type {number} */
const SECTION_VOLUME = 16 * 16 * 16;
/** Columns per chunk. @type {number} */
const COLUMN_COUNT = 16 * 16;
/** Voxels in the padded 18^3 mesh input. @type {number} */
const PAD_VOLUME = 18 * 18 * 18;
/** Columns in the padded 18x18 biome plane. @type {number} */
const PAD_AREA = 18 * 18;

/** The generator this worker was initialised with. @type {WorldGenerator|null} */
let generator = null;
/** Seed the generator was built for. @type {number} */
let workerSeed = 0;
/** Reusable mesher buffers; one set per worker, never shared. */
const meshScratch = createMeshScratch();
/** Chunks generated by this worker. @type {number} */
let genCount = 0;
/** Sections meshed by this worker. @type {number} */
let meshCount = 0;

/**
 * Post a message back to the main thread, transferring the given buffers.
 * @param {Object} msg Message payload.
 * @param {ArrayBuffer[]} [transfer] Buffers to transfer.
 * @returns {void}
 */
function post(msg, transfer) {
  if (transfer && transfer.length !== 0) self.postMessage(msg, transfer);
  else self.postMessage(msg);
}

/**
 * Report a failure instead of letting the worker die.
 * @param {number} id Job id the failure belongs to (0 when unattributed).
 * @param {Error|string} error The failure.
 * @returns {void}
 */
function postError(id, error) {
  const err = error instanceof Error ? error : new Error(String(error));
  post({
    type: 'error',
    id: id | 0,
    message: err.message || String(err),
    stack: typeof err.stack === 'string' ? err.stack : '',
  });
}

/**
 * Append a buffer to a transfer list, skipping duplicates.
 * @param {ArrayBuffer[]} list Transfer list.
 * @param {Set<ArrayBuffer>} seen Buffers already queued.
 * @param {ArrayBuffer|null|undefined} buffer Candidate buffer.
 * @returns {void}
 */
function addTransfer(list, seen, buffer) {
  if (!buffer || !(buffer instanceof ArrayBuffer) || seen.has(buffer)) return;
  seen.add(buffer);
  list.push(buffer);
}

/**
 * Coerce generator output into a `Uint16Array` of the expected length.
 * @param {*} src Source data.
 * @param {number} length Expected element count.
 * @returns {Uint16Array|null} Normalised array, or `null`.
 */
function asUint16(src, length) {
  if (src === null || src === undefined) return null;
  if (src instanceof Uint16Array) return src.length === length ? src : new Uint16Array(src.subarray(0, length));
  if (src instanceof ArrayBuffer) {
    return src.byteLength >= length * 2 ? new Uint16Array(src, 0, length) : null;
  }
  if (ArrayBuffer.isView(src)) return Uint16Array.from(/** @type {ArrayLike<number>} */ (src));
  if (Array.isArray(src)) return Uint16Array.from(src);
  return null;
}

/**
 * Coerce generator output into an `Int16Array` of the expected length.
 * @param {*} src Source data.
 * @param {number} length Expected element count.
 * @returns {Int16Array|null} Normalised array, or `null`.
 */
function asInt16(src, length) {
  if (src === null || src === undefined) return null;
  if (src instanceof Int16Array) return src.length === length ? src : new Int16Array(src.subarray(0, length));
  if (src instanceof ArrayBuffer) {
    return src.byteLength >= length * 2 ? new Int16Array(src, 0, length) : null;
  }
  if (ArrayBuffer.isView(src)) return Int16Array.from(/** @type {ArrayLike<number>} */ (src));
  if (Array.isArray(src)) return Int16Array.from(src);
  return null;
}

/**
 * Coerce generator output into a `Uint8Array` of the expected length.
 * @param {*} src Source data.
 * @param {number} length Expected element count.
 * @returns {Uint8Array|null} Normalised array, or `null`.
 */
function asUint8(src, length) {
  if (src === null || src === undefined) return null;
  if (src instanceof Uint8Array) return src.length === length ? src : new Uint8Array(src.subarray(0, length));
  if (src instanceof ArrayBuffer) {
    return src.byteLength >= length ? new Uint8Array(src, 0, length) : null;
  }
  if (ArrayBuffer.isView(src)) return Uint8Array.from(/** @type {ArrayLike<number>} */ (src));
  if (Array.isArray(src)) return Uint8Array.from(src);
  return null;
}

/**
 * Flatten one chunk's deferred edits into `x, y, z, blockId` quadruplets.
 * Accepts both the tuple form (`[[x,y,z,id], ...]`) and an already flat list.
 * @param {Array<number[]>|number[]|Int32Array|null|undefined} list Edit list.
 * @returns {Int32Array|null} Flat edits, or `null` when there is nothing to send.
 */
function flattenEdits(list) {
  if (!list) return null;
  if (list instanceof Int32Array) {
    const n = list.length - (list.length % 4);
    return n === 0 ? null : (n === list.length ? list : list.slice(0, n));
  }
  if (!Array.isArray(list) || list.length === 0) return null;
  if (typeof list[0] === 'number') {
    const n = list.length - (list.length % 4);
    if (n === 0) return null;
    const flat = new Int32Array(n);
    for (let i = 0; i < n; i++) flat[i] = list[i] | 0;
    return flat;
  }
  const flat = new Int32Array(list.length * 4);
  let n = 0;
  for (let i = 0; i < list.length; i++) {
    const e = list[i];
    if (!e || e.length < 4) continue;
    flat[n] = e[0] | 0;
    flat[n + 1] = e[1] | 0;
    flat[n + 2] = e[2] | 0;
    flat[n + 3] = e[3] | 0;
    n += 4;
  }
  if (n === 0) return null;
  return n === flat.length ? flat : flat.slice(0, n);
}

/**
 * Drain the generator's pending cross-chunk edits into a transferable form.
 * @param {ArrayBuffer[]} transfer Transfer list to extend.
 * @param {Set<ArrayBuffer>} seen Buffers already queued.
 * @returns {Array<[string, Int32Array]>} `[chunkKey, flatEdits]` pairs.
 */
function takeEdits(transfer, seen) {
  /** @type {Array<[string, Int32Array]>} */
  const out = [];
  if (generator === null || typeof generator.takePendingEdits !== 'function') return out;
  const map = generator.takePendingEdits();
  if (!map || typeof map[Symbol.iterator] !== 'function') return out;
  for (const entry of map) {
    if (!entry || entry.length < 2) continue;
    const key = entry[0];
    if (typeof key !== 'string') continue;
    const flat = flattenEdits(entry[1]);
    if (flat === null) continue;
    out.push([key, flat]);
    addTransfer(transfer, seen, flat.buffer);
  }
  return out;
}

/**
 * Build the generator (spec 5.9) and acknowledge readiness.
 * @param {{id?:number, seed?:number, options?:Object}} msg Init message.
 * @returns {void}
 */
function handleInit(msg) {
  workerSeed = Number.isFinite(msg.seed) ? (msg.seed | 0) : 0;
  // Biome surface/sub-surface/underwater block names resolve lazily; wiring the
  // registry up front keeps the generator's inner loops free of dynamic imports.
  resolveBiomeBlocks(BLOCK_BY_NAME);
  generator = new WorldGenerator(workerSeed, msg.options || {});
  post({
    type: 'ready',
    id: msg.id === undefined ? 0 : (msg.id | 0),
    seed: workerSeed,
    genVersion: GEN_VERSION,
    vertexStride: VERTEX_STRIDE,
    blocks: BLOCK_COUNT,
    structures: Object.keys(STRUCTURES).length,
  });
}

/**
 * Generate one chunk column and post it back (spec 5.9 shape).
 * @param {{id:number, cx:number, cz:number}} msg Generation job.
 * @returns {void}
 */
function handleGen(msg) {
  if (generator === null) throw new Error('world worker received a "gen" job before "init"');
  const cx = msg.cx | 0;
  const cz = msg.cz | 0;
  const result = generator.generateChunk(cx, cz);
  if (!result) throw new Error(`generateChunk(${cx}, ${cz}) returned nothing`);

  /** @type {ArrayBuffer[]} */
  const transfer = [];
  const seen = new Set();

  /** @type {(Uint16Array|null)[]} */
  const sections = new Array(SECTION_COUNT).fill(null);
  const src = result.sections || [];
  for (let sy = 0; sy < SECTION_COUNT; sy++) {
    const blocks = asUint16(src[sy], SECTION_VOLUME);
    if (blocks === null) continue;
    sections[sy] = blocks;
    addTransfer(transfer, seen, blocks.buffer);
  }

  const heightmap = asInt16(result.heightmap, COLUMN_COUNT);
  if (heightmap !== null) addTransfer(transfer, seen, heightmap.buffer);
  const biomes = asUint8(result.biomes, COLUMN_COUNT);
  if (biomes !== null) addTransfer(transfer, seen, biomes.buffer);
  const oceanFloor = asInt16(result.oceanFloor, COLUMN_COUNT);
  if (oceanFloor !== null) addTransfer(transfer, seen, oceanFloor.buffer);

  const edits = takeEdits(transfer, seen);
  genCount++;
  post({
    type: 'gen',
    id: msg.id | 0,
    cx,
    cz,
    sections,
    heightmap,
    biomes,
    oceanFloor,
    edits,
  }, transfer);
}

/**
 * Mesh one padded section and post the three render buckets back (spec 5.13).
 * @param {{id:number, cx:number, cz:number, sy:number, blocks:*, light:*,
 *   biomes:*, smoothLighting?:boolean, fancyLeaves?:boolean}} msg Mesh job.
 * @returns {void}
 */
function handleMesh(msg) {
  const blocks = asUint16(msg.blocks, PAD_VOLUME);
  if (blocks === null) throw new Error('mesh job is missing its padded block volume');
  const light = asUint16(msg.light, PAD_VOLUME);
  const biomes = asUint8(msg.biomes, PAD_AREA);
  const result = meshSectionInto({
    blocks,
    light: light === null ? new Uint16Array(PAD_VOLUME) : light,
    biomes: biomes === null ? new Uint8Array(PAD_AREA) : biomes,
    sy: msg.sy | 0,
    smoothLighting: msg.smoothLighting !== false,
    fancyLeaves: msg.fancyLeaves !== false,
  }, meshScratch);

  /** @type {ArrayBuffer[]} */
  const transfer = [];
  const seen = new Set();
  addTransfer(transfer, seen, result.opaque.vertices);
  addTransfer(transfer, seen, result.opaque.indices);
  addTransfer(transfer, seen, result.cutout.vertices);
  addTransfer(transfer, seen, result.cutout.indices);
  addTransfer(transfer, seen, result.water.vertices);
  addTransfer(transfer, seen, result.water.indices);
  meshCount++;
  post({
    type: 'mesh',
    id: msg.id | 0,
    cx: msg.cx | 0,
    cz: msg.cz | 0,
    sy: msg.sy | 0,
    opaque: result.opaque,
    cutout: result.cutout,
    water: result.water,
  }, transfer);
}

/**
 * Release the generator and close the worker.
 * @param {{id?:number}} msg Dispose message.
 * @returns {void}
 */
function handleDispose(msg) {
  post({
    type: 'disposed',
    id: msg && msg.id !== undefined ? (msg.id | 0) : 0,
    generated: genCount,
    meshed: meshCount,
  });
  generator = null;
  self.close();
}

/**
 * Single message entry point. Any failure is reported, never thrown.
 * @param {MessageEvent} event Incoming message.
 * @returns {void}
 */
function onMessage(event) {
  const msg = event.data;
  if (!msg || typeof msg.type !== 'string') return;
  try {
    switch (msg.type) {
      case 'init':
        handleInit(msg);
        break;
      case 'gen':
        handleGen(msg);
        break;
      case 'mesh':
        handleMesh(msg);
        break;
      case 'dispose':
        handleDispose(msg);
        break;
      default:
        postError(msg.id === undefined ? 0 : msg.id, new Error(`unknown world worker message "${msg.type}"`));
        break;
    }
  } catch (err) {
    postError(msg.id === undefined ? 0 : msg.id, /** @type {Error} */ (err));
  }
}

self.addEventListener('message', onMessage);

self.addEventListener('error', (event) => {
  postError(0, event && event.message ? new Error(event.message) : new Error('world worker error'));
});

self.addEventListener('unhandledrejection', (event) => {
  const reason = event && event.reason !== undefined ? event.reason : 'unhandled rejection in world worker';
  postError(0, reason instanceof Error ? reason : new Error(String(reason)));
});
