let tiere=[
  {
    "name": "Amphiprion ocellaris (Ocellaris Clownfisch)",
    "type": "fish",
    "min": 120,
    "size": "6-11cm",
    "temp": "24-27°C",
    "flow": "mittel",
    "light": "-",
    "food": "Artemia-Nauplien, Artemia, adult (Salzwasserkrebschen), Austerneier, Cyclops (Ruderfußkrebse), Flockenfutter, Flohkrebse (Amphipoden, Gammarus), Frostfutter (große Sorten), Futtergranulat, Invertebraten (Wirbellose), Krill (Euphausiidae), Lebendfutter, Lobstereier, Mysis (Schwebegarnelen), Ruderfußkrebse (Copepoden), Salzwasserflöhe (Cladocera), Zooplankton (Tierisches Plankton) ",
    "agg": "⭐⭐",
    "reef": "Ja",
    "form": "Einzel/Paar",
    "note": "-",
    "img": "assets/img/fish.png"
  },
  {
    "name": "Amphiprion percula (Percula Clownfisch)",
    "type": "fish",
    "min": 150,
    "size": "8-11cm",
    "temp": "24-26°C",
    "flow": "mittel",
    "light": "-",
    "food": "Frost/Granulat",
    "agg": "⭐⭐",
    "reef": "Ja",
    "form": "Einzel/Paar",
    "note": "-",
    "img": "assets/img/fish.png"
  },
  {
    "name": "Chromis viridis (Blaue Riffbarsche)",
    "type": "fish",
    "min": 200,
    "size": "6-8cm",
    "temp": "24-26°C",
    "flow": "mittel",
    "light": "-",
    "food": "Frost/Granulat",
    "agg": "⭐",
    "reef": "Ja",
    "form": "Einzel/Paar",
    "note": "-",
    "img": "assets/img/fish.png"
  },
  {
    "name": "Pterapogon kauderni (Banggai Kardinal)",
    "type": "fish",
    "min": 200,
    "size": "8cm",
    "temp": "24-26°C",
    "flow": "mittel",
    "light": "-",
    "food": "Frost/Granulat",
    "agg": "⭐",
    "reef": "Ja",
    "form": "Einzel/Paar",
    "note": "-",
    "img": "assets/img/fish.png"
  },
  {
    "name": "Halichoeres chrysus (Gelber Juwelenlippfisch)",
    "type": "fish",
    "min": 250,
    "size": "12cm",
    "temp": "24-26°C",
    "flow": "mittel",
    "light": "-",
    "food": "Frost/Granulat",
    "agg": "⭐⭐",
    "reef": "Bedingt",
    "form": "Einzel/Paar",
    "note": "-",
    "img": "assets/img/fish.png"
  },
  {
    "name": "Centropyge bispinosa (Coral Beauty Zwergkaiser)",
    "type": "fish",
    "min": 250,
    "size": "10cm",
    "temp": "24-26°C",
    "flow": "mittel",
    "light": "-",
    "food": "Frost/Granulat",
    "agg": "⭐⭐⭐",
    "reef": "Bedingt",
    "form": "Einzel/Paar",
    "note": "-",
    "img": "assets/img/fish.png"
  },
  {
    "name": "Centropyge loricula (Flammenzwergkaiser)",
    "type": "fish",
    "min": 250,
    "size": "10cm",
    "temp": "24-26°C",
    "flow": "mittel",
    "light": "-",
    "food": "Frost/Granulat",
    "agg": "⭐⭐⭐",
    "reef": "Bedingt",
    "form": "Einzel/Paar",
    "note": "-",
    "img": "assets/img/fish.png"
  },
  {
    "name": "Zebrasoma flavescens (Gelber Doktor)",
    "type": "fish",
    "min": 300,
    "size": "20cm",
    "temp": "24-26°C",
    "flow": "mittel",
    "light": "-",
    "food": "Frost/Granulat",
    "agg": "⭐⭐⭐",
    "reef": "Ja",
    "form": "Einzel/Paar",
    "note": "-",
    "img": "assets/img/fish.png"
  },
  {
    "name": "Ctenochaetus tominiensis (Tomini Doktor)",
    "type": "fish",
    "min": 300,
    "size": "15cm",
    "temp": "24-26°C",
    "flow": "mittel",
    "light": "-",
    "food": "Frost/Granulat",
    "agg": "⭐⭐⭐",
    "reef": "Ja",
    "form": "Einzel/Paar",
    "note": "-",
    "img": "assets/img/fish.png"
  },
  {
    "name": "Paracanthurus hepatus (Palettendoktor)",
    "type": "fish",
    "min": 450,
    "size": "25cm",
    "temp": "24-26°C",
    "flow": "mittel",
    "light": "-",
    "food": "Frost/Granulat",
    "agg": "⭐⭐⭐⭐",
    "reef": "Bedingt",
    "form": "Einzel/Paar",
    "note": "-",
    "img": "assets/img/fish.png"
  },
  {
    "name": "Amphiprion ocellaris 10 (Ocellaris Clownfisch)",
    "type": "fish",
    "min": 150,
    "size": "8-11cm",
    "temp": "24-26°C",
    "flow": "mittel",
    "light": "-",
    "food": "Frost/Granulat",
    "agg": "⭐⭐",
    "reef": "Ja",
    "form": "Einzel/Paar",
    "note": "Variante",
    "img": "assets/img/fish.png"
  },
  {
    "name": "Amphiprion percula 11 (Percula Clownfisch)",
    "type": "fish",
    "min": 150,
    "size": "8-11cm",
    "temp": "24-26°C",
    "flow": "mittel",
    "light": "-",
    "food": "Frost/Granulat",
    "agg": "⭐⭐",
    "reef": "Ja",
    "form": "Einzel/Paar",
    "note": "Variante",
    "img": "assets/img/fish.png"
  },
  {
    "name": "Chromis viridis 12 (Blaue Riffbarsche)",
    "type": "fish",
    "min": 200,
    "size": "6-8cm",
    "temp": "24-26°C",
    "flow": "mittel",
    "light": "-",
    "food": "Frost/Granulat",
    "agg": "⭐",
    "reef": "Ja",
    "form": "Einzel/Paar",
    "note": "Variante",
    "img": "assets/img/fish.png"
  },
  {
    "name": "Pterapogon kauderni 13 (Banggai Kardinal)",
    "type": "fish",
    "min": 200,
    "size": "8cm",
    "temp": "24-26°C",
    "flow": "mittel",
    "light": "-",
    "food": "Frost/Granulat",
    "agg": "⭐",
    "reef": "Ja",
    "form": "Einzel/Paar",
    "note": "Variante",
    "img": "assets/img/fish.png"
  },
  {
    "name": "Halichoeres chrysus 14 (Gelber Juwelenlippfisch)",
    "type": "fish",
    "min": 250,
    "size": "12cm",
    "temp": "24-26°C",
    "flow": "mittel",
    "light": "-",
    "food": "Frost/Granulat",
    "agg": "⭐⭐",
    "reef": "Bedingt",
    "form": "Einzel/Paar",
    "note": "Variante",
    "img": "assets/img/fish.png"
  },
  {
    "name": "Centropyge bispinosa 15 (Coral Beauty Zwergkaiser)",
    "type": "fish",
    "min": 250,
    "size": "10cm",
    "temp": "24-26°C",
    "flow": "mittel",
    "light": "-",
    "food": "Frost/Granulat",
    "agg": "⭐⭐⭐",
    "reef": "Bedingt",
    "form": "Einzel/Paar",
    "note": "Variante",
    "img": "assets/img/fish.png"
  },
  {
    "name": "Centropyge loricula 16 (Flammenzwergkaiser)",
    "type": "fish",
    "min": 250,
    "size": "10cm",
    "temp": "24-26°C",
    "flow": "mittel",
    "light": "-",
    "food": "Frost/Granulat",
    "agg": "⭐⭐⭐",
    "reef": "Bedingt",
    "form": "Einzel/Paar",
    "note": "Variante",
    "img": "assets/img/fish.png"
  },
  {
    "name": "Zebrasoma flavescens 17 (Gelber Doktor)",
    "type": "fish",
    "min": 300,
    "size": "20cm",
    "temp": "24-26°C",
    "flow": "mittel",
    "light": "-",
    "food": "Frost/Granulat",
    "agg": "⭐⭐⭐",
    "reef": "Ja",
    "form": "Einzel/Paar",
    "note": "Variante",
    "img": "assets/img/fish.png"
  },
  {
    "name": "Ctenochaetus tominiensis 18 (Tomini Doktor)",
    "type": "fish",
    "min": 300,
    "size": "15cm",
    "temp": "24-26°C",
    "flow": "mittel",
    "light": "-",
    "food": "Frost/Granulat",
    "agg": "⭐⭐⭐",
    "reef": "Ja",
    "form": "Einzel/Paar",
    "note": "Variante",
    "img": "assets/img/fish.png"
  },
  {
    "name": "Paracanthurus hepatus 19 (Palettendoktor)",
    "type": "fish",
    "min": 450,
    "size": "25cm",
    "temp": "24-26°C",
    "flow": "mittel",
    "light": "-",
    "food": "Frost/Granulat",
    "agg": "⭐⭐⭐⭐",
    "reef": "Bedingt",
    "form": "Einzel/Paar",
    "note": "Variante",
    "img": "assets/img/fish.png"
  },
  {
    "name": "Amphiprion ocellaris 20 (Ocellaris Clownfisch)",
    "type": "fish",
    "min": 150,
    "size": "8-11cm",
    "temp": "24-26°C",
    "flow": "mittel",
    "light": "-",
    "food": "Frost/Granulat",
    "agg": "⭐⭐",
    "reef": "Ja",
    "form": "Einzel/Paar",
    "note": "Variante",
    "img": "assets/img/fish.png"
  },
  {
    "name": "Amphiprion percula 21 (Percula Clownfisch)",
    "type": "fish",
    "min": 150,
    "size": "8-11cm",
    "temp": "24-26°C",
    "flow": "mittel",
    "light": "-",
    "food": "Frost/Granulat",
    "agg": "⭐⭐",
    "reef": "Ja",
    "form": "Einzel/Paar",
    "note": "Variante",
    "img": "assets/img/fish.png"
  },
  {
    "name": "Chromis viridis 22 (Blaue Riffbarsche)",
    "type": "fish",
    "min": 200,
    "size": "6-8cm",
    "temp": "24-26°C",
    "flow": "mittel",
    "light": "-",
    "food": "Frost/Granulat",
    "agg": "⭐",
    "reef": "Ja",
    "form": "Einzel/Paar",
    "note": "Variante",
    "img": "assets/img/fish.png"
  },
  {
    "name": "Pterapogon kauderni 23 (Banggai Kardinal)",
    "type": "fish",
    "min": 200,
    "size": "8cm",
    "temp": "24-26°C",
    "flow": "mittel",
    "light": "-",
    "food": "Frost/Granulat",
    "agg": "⭐",
    "reef": "Ja",
    "form": "Einzel/Paar",
    "note": "Variante",
    "img": "assets/img/fish.png"
  },
  {
    "name": "Halichoeres chrysus 24 (Gelber Juwelenlippfisch)",
    "type": "fish",
    "min": 250,
    "size": "12cm",
    "temp": "24-26°C",
    "flow": "mittel",
    "light": "-",
    "food": "Frost/Granulat",
    "agg": "⭐⭐",
    "reef": "Bedingt",
    "form": "Einzel/Paar",
    "note": "Variante",
    "img": "assets/img/fish.png"
  },
  {
    "name": "Centropyge bispinosa 25 (Coral Beauty Zwergkaiser)",
    "type": "fish",
    "min": 250,
    "size": "10cm",
    "temp": "24-26°C",
    "flow": "mittel",
    "light": "-",
    "food": "Frost/Granulat",
    "agg": "⭐⭐⭐",
    "reef": "Bedingt",
    "form": "Einzel/Paar",
    "note": "Variante",
    "img": "assets/img/fish.png"
  },
  {
    "name": "Centropyge loricula 26 (Flammenzwergkaiser)",
    "type": "fish",
    "min": 250,
    "size": "10cm",
    "temp": "24-26°C",
    "flow": "mittel",
    "light": "-",
    "food": "Frost/Granulat",
    "agg": "⭐⭐⭐",
    "reef": "Bedingt",
    "form": "Einzel/Paar",
    "note": "Variante",
    "img": "assets/img/fish.png"
  },
  {
    "name": "Zebrasoma flavescens 27 (Gelber Doktor)",
    "type": "fish",
    "min": 300,
    "size": "20cm",
    "temp": "24-26°C",
    "flow": "mittel",
    "light": "-",
    "food": "Frost/Granulat",
    "agg": "⭐⭐⭐",
    "reef": "Ja",
    "form": "Einzel/Paar",
    "note": "Variante",
    "img": "assets/img/fish.png"
  },
  {
    "name": "Ctenochaetus tominiensis 28 (Tomini Doktor)",
    "type": "fish",
    "min": 300,
    "size": "15cm",
    "temp": "24-26°C",
    "flow": "mittel",
    "light": "-",
    "food": "Frost/Granulat",
    "agg": "⭐⭐⭐",
    "reef": "Ja",
    "form": "Einzel/Paar",
    "note": "Variante",
    "img": "assets/img/fish.png"
  },
  {
    "name": "Paracanthurus hepatus 29 (Palettendoktor)",
    "type": "fish",
    "min": 450,
    "size": "25cm",
    "temp": "24-26°C",
    "flow": "mittel",
    "light": "-",
    "food": "Frost/Granulat",
    "agg": "⭐⭐⭐⭐",
    "reef": "Bedingt",
    "form": "Einzel/Paar",
    "note": "Variante",
    "img": "assets/img/fish.png"
  },
  {
    "name": "Lysmata amboinensis (Weißband-Putzer)",
    "type": "invert",
    "min": 60,
    "size": "3-7cm",
    "temp": "24-26°C",
    "flow": "mittel",
    "light": "-",
    "food": "Algen/Rest",
    "agg": "⭐",
    "reef": "Ja",
    "form": "-",
    "note": "-",
    "img": "assets/img/invert.png"
  },
  {
    "name": "Lysmata wurdemanni (Pfefferminz Garnele)",
    "type": "invert",
    "min": 60,
    "size": "3-7cm",
    "temp": "24-26°C",
    "flow": "mittel",
    "light": "-",
    "food": "Algen/Rest",
    "agg": "⭐",
    "reef": "Ja",
    "form": "-",
    "note": "-",
    "img": "assets/img/invert.png"
  },
  {
    "name": "Stenopus hispidus (Putzergarnele)",
    "type": "invert",
    "min": 100,
    "size": "3-7cm",
    "temp": "24-26°C",
    "flow": "mittel",
    "light": "-",
    "food": "Algen/Rest",
    "agg": "⭐",
    "reef": "Ja",
    "form": "-",
    "note": "-",
    "img": "assets/img/invert.png"
  },
  {
    "name": "Calcinus elegans (Einsiedler Krebs)",
    "type": "invert",
    "min": 60,
    "size": "3-7cm",
    "temp": "24-26°C",
    "flow": "mittel",
    "light": "-",
    "food": "Algen/Rest",
    "agg": "⭐",
    "reef": "Ja",
    "form": "-",
    "note": "-",
    "img": "assets/img/invert.png"
  },
  {
    "name": "Turbo fluctuosa (Turbo Schnecke)",
    "type": "invert",
    "min": 40,
    "size": "3-7cm",
    "temp": "24-26°C",
    "flow": "mittel",
    "light": "-",
    "food": "Algen/Rest",
    "agg": "⭐",
    "reef": "Ja",
    "form": "-",
    "note": "-",
    "img": "assets/img/invert.png"
  },
  {
    "name": "Mespilia globulus (Tuxedo Seeigel)",
    "type": "invert",
    "min": 80,
    "size": "3-7cm",
    "temp": "24-26°C",
    "flow": "mittel",
    "light": "-",
    "food": "Algen/Rest",
    "agg": "⭐",
    "reef": "Ja",
    "form": "-",
    "note": "-",
    "img": "assets/img/invert.png"
  },
  {
    "name": "Lysmata amboinensis 6 (Weißband-Putzer)",
    "type": "invert",
    "min": 60,
    "size": "3-7cm",
    "temp": "24-26°C",
    "flow": "mittel",
    "light": "-",
    "food": "Algen/Rest",
    "agg": "⭐",
    "reef": "Ja",
    "form": "-",
    "note": "Variante",
    "img": "assets/img/invert.png"
  },
  {
    "name": "Lysmata wurdemanni 7 (Pfefferminz Garnele)",
    "type": "invert",
    "min": 60,
    "size": "3-7cm",
    "temp": "24-26°C",
    "flow": "mittel",
    "light": "-",
    "food": "Algen/Rest",
    "agg": "⭐",
    "reef": "Ja",
    "form": "-",
    "note": "Variante",
    "img": "assets/img/invert.png"
  },
  {
    "name": "Stenopus hispidus 8 (Putzergarnele)",
    "type": "invert",
    "min": 100,
    "size": "3-7cm",
    "temp": "24-26°C",
    "flow": "mittel",
    "light": "-",
    "food": "Algen/Rest",
    "agg": "⭐",
    "reef": "Ja",
    "form": "-",
    "note": "Variante",
    "img": "assets/img/invert.png"
  },
  {
    "name": "Calcinus elegans 9 (Einsiedler Krebs)",
    "type": "invert",
    "min": 60,
    "size": "3-7cm",
    "temp": "24-26°C",
    "flow": "mittel",
    "light": "-",
    "food": "Algen/Rest",
    "agg": "⭐",
    "reef": "Ja",
    "form": "-",
    "note": "Variante",
    "img": "assets/img/invert.png"
  },
  {
    "name": "Turbo fluctuosa 10 (Turbo Schnecke)",
    "type": "invert",
    "min": 40,
    "size": "3-7cm",
    "temp": "24-26°C",
    "flow": "mittel",
    "light": "-",
    "food": "Algen/Rest",
    "agg": "⭐",
    "reef": "Ja",
    "form": "-",
    "note": "Variante",
    "img": "assets/img/invert.png"
  },
  {
    "name": "Mespilia globulus 11 (Tuxedo Seeigel)",
    "type": "invert",
    "min": 80,
    "size": "3-7cm",
    "temp": "24-26°C",
    "flow": "mittel",
    "light": "-",
    "food": "Algen/Rest",
    "agg": "⭐",
    "reef": "Ja",
    "form": "-",
    "note": "Variante",
    "img": "assets/img/invert.png"
  },
  {
    "name": "Lysmata amboinensis 12 (Weißband-Putzer)",
    "type": "invert",
    "min": 60,
    "size": "3-7cm",
    "temp": "24-26°C",
    "flow": "mittel",
    "light": "-",
    "food": "Algen/Rest",
    "agg": "⭐",
    "reef": "Ja",
    "form": "-",
    "note": "Variante",
    "img": "assets/img/invert.png"
  },
  {
    "name": "Lysmata wurdemanni 13 (Pfefferminz Garnele)",
    "type": "invert",
    "min": 60,
    "size": "3-7cm",
    "temp": "24-26°C",
    "flow": "mittel",
    "light": "-",
    "food": "Algen/Rest",
    "agg": "⭐",
    "reef": "Ja",
    "form": "-",
    "note": "Variante",
    "img": "assets/img/invert.png"
  },
  {
    "name": "Stenopus hispidus 14 (Putzergarnele)",
    "type": "invert",
    "min": 100,
    "size": "3-7cm",
    "temp": "24-26°C",
    "flow": "mittel",
    "light": "-",
    "food": "Algen/Rest",
    "agg": "⭐",
    "reef": "Ja",
    "form": "-",
    "note": "Variante",
    "img": "assets/img/invert.png"
  },
  {
    "name": "Calcinus elegans 15 (Einsiedler Krebs)",
    "type": "invert",
    "min": 60,
    "size": "3-7cm",
    "temp": "24-26°C",
    "flow": "mittel",
    "light": "-",
    "food": "Algen/Rest",
    "agg": "⭐",
    "reef": "Ja",
    "form": "-",
    "note": "Variante",
    "img": "assets/img/invert.png"
  },
  {
    "name": "Turbo fluctuosa 16 (Turbo Schnecke)",
    "type": "invert",
    "min": 40,
    "size": "3-7cm",
    "temp": "24-26°C",
    "flow": "mittel",
    "light": "-",
    "food": "Algen/Rest",
    "agg": "⭐",
    "reef": "Ja",
    "form": "-",
    "note": "Variante",
    "img": "assets/img/invert.png"
  },
  {
    "name": "Mespilia globulus 17 (Tuxedo Seeigel)",
    "type": "invert",
    "min": 80,
    "size": "3-7cm",
    "temp": "24-26°C",
    "flow": "mittel",
    "light": "-",
    "food": "Algen/Rest",
    "agg": "⭐",
    "reef": "Ja",
    "form": "-",
    "note": "Variante",
    "img": "assets/img/invert.png"
  },
  {
    "name": "Lysmata amboinensis 18 (Weißband-Putzer)",
    "type": "invert",
    "min": 60,
    "size": "3-7cm",
    "temp": "24-26°C",
    "flow": "mittel",
    "light": "-",
    "food": "Algen/Rest",
    "agg": "⭐",
    "reef": "Ja",
    "form": "-",
    "note": "Variante",
    "img": "assets/img/invert.png"
  },
  {
    "name": "Lysmata wurdemanni 19 (Pfefferminz Garnele)",
    "type": "invert",
    "min": 60,
    "size": "3-7cm",
    "temp": "24-26°C",
    "flow": "mittel",
    "light": "-",
    "food": "Algen/Rest",
    "agg": "⭐",
    "reef": "Ja",
    "form": "-",
    "note": "Variante",
    "img": "assets/img/invert.png"
  },
  {
    "name": "Zoanthus spp. (Zoanthus)",
    "type": "coral",
    "min": 0,
    "size": "Kolonie",
    "temp": "24-26°C",
    "flow": "mittel",
    "light": "mittel",
    "food": "Licht/Partikel",
    "agg": "⭐",
    "reef": "Ja",
    "form": "Kolonie",
    "note": "-",
    "img": "assets/img/coral.png"
  },
  {
    "name": "Xenia spp. (Xenia)",
    "type": "coral",
    "min": 0,
    "size": "Kolonie",
    "temp": "24-26°C",
    "flow": "niedrig",
    "light": "mittel",
    "food": "Licht/Partikel",
    "agg": "⭐",
    "reef": "Ja",
    "form": "Kolonie",
    "note": "-",
    "img": "assets/img/coral.png"
  },
  {
    "name": "Sarcophyton (Lederkoralle)",
    "type": "coral",
    "min": 0,
    "size": "Kolonie",
    "temp": "24-26°C",
    "flow": "mittel",
    "light": "mittel",
    "food": "Licht/Partikel",
    "agg": "⭐⭐",
    "reef": "Ja",
    "form": "Kolonie",
    "note": "-",
    "img": "assets/img/coral.png"
  },
  {
    "name": "Ricordea florida (Ricordea)",
    "type": "coral",
    "min": 0,
    "size": "Kolonie",
    "temp": "24-26°C",
    "flow": "niedrig",
    "light": "mittel",
    "food": "Licht/Partikel",
    "agg": "⭐",
    "reef": "Ja",
    "form": "Kolonie",
    "note": "-",
    "img": "assets/img/coral.png"
  },
  {
    "name": "Euphyllia glabrescens (Torch)",
    "type": "coral",
    "min": 0,
    "size": "Kolonie",
    "temp": "24-26°C",
    "flow": "mittel",
    "light": "mittel",
    "food": "Licht/Partikel",
    "agg": "⭐⭐",
    "reef": "Ja",
    "form": "Kolonie",
    "note": "-",
    "img": "assets/img/coral.png"
  },
  {
    "name": "Acanthastrea spp. (Acan)",
    "type": "coral",
    "min": 0,
    "size": "Kolonie",
    "temp": "24-26°C",
    "flow": "niedrig",
    "light": "niedrig",
    "food": "Licht/Partikel",
    "agg": "⭐",
    "reef": "Ja",
    "form": "Kolonie",
    "note": "-",
    "img": "assets/img/coral.png"
  },
  {
    "name": "Acropora spp. (Acropora)",
    "type": "coral",
    "min": 0,
    "size": "Kolonie",
    "temp": "24-26°C",
    "flow": "hoch",
    "light": "hoch",
    "food": "Licht/Partikel",
    "agg": "⭐⭐⭐",
    "reef": "Bedingt",
    "form": "Kolonie",
    "note": "-",
    "img": "assets/img/coral.png"
  },
  {
    "name": "Montipora digitata (Montipora)",
    "type": "coral",
    "min": 0,
    "size": "Kolonie",
    "temp": "24-26°C",
    "flow": "mittel-hoch",
    "light": "hoch",
    "food": "Licht/Partikel",
    "agg": "⭐⭐",
    "reef": "Bedingt",
    "form": "Kolonie",
    "note": "-",
    "img": "assets/img/coral.png"
  },
  {
    "name": "Zoanthus spp. 8 (Zoanthus)",
    "type": "coral",
    "min": 0,
    "size": "Kolonie",
    "temp": "24-26°C",
    "flow": "mittel",
    "light": "mittel",
    "food": "Licht/Partikel",
    "agg": "⭐",
    "reef": "Ja",
    "form": "Kolonie",
    "note": "Variante",
    "img": "assets/img/coral.png"
  },
  {
    "name": "Xenia spp. 9 (Xenia)",
    "type": "coral",
    "min": 0,
    "size": "Kolonie",
    "temp": "24-26°C",
    "flow": "niedrig",
    "light": "mittel",
    "food": "Licht/Partikel",
    "agg": "⭐",
    "reef": "Ja",
    "form": "Kolonie",
    "note": "Variante",
    "img": "assets/img/coral.png"
  },
  {
    "name": "Sarcophyton 10 (Lederkoralle)",
    "type": "coral",
    "min": 0,
    "size": "Kolonie",
    "temp": "24-26°C",
    "flow": "mittel",
    "light": "mittel",
    "food": "Licht/Partikel",
    "agg": "⭐⭐",
    "reef": "Ja",
    "form": "Kolonie",
    "note": "Variante",
    "img": "assets/img/coral.png"
  },
  {
    "name": "Ricordea florida 11 (Ricordea)",
    "type": "coral",
    "min": 0,
    "size": "Kolonie",
    "temp": "24-26°C",
    "flow": "niedrig",
    "light": "mittel",
    "food": "Licht/Partikel",
    "agg": "⭐",
    "reef": "Ja",
    "form": "Kolonie",
    "note": "Variante",
    "img": "assets/img/coral.png"
  },
  {
    "name": "Euphyllia glabrescens 12 (Torch)",
    "type": "coral",
    "min": 0,
    "size": "Kolonie",
    "temp": "24-26°C",
    "flow": "mittel",
    "light": "mittel",
    "food": "Licht/Partikel",
    "agg": "⭐⭐",
    "reef": "Ja",
    "form": "Kolonie",
    "note": "Variante",
    "img": "assets/img/coral.png"
  },
  {
    "name": "Acanthastrea spp. 13 (Acan)",
    "type": "coral",
    "min": 0,
    "size": "Kolonie",
    "temp": "24-26°C",
    "flow": "niedrig",
    "light": "niedrig",
    "food": "Licht/Partikel",
    "agg": "⭐",
    "reef": "Ja",
    "form": "Kolonie",
    "note": "Variante",
    "img": "assets/img/coral.png"
  },
  {
    "name": "Acropora spp. 14 (Acropora)",
    "type": "coral",
    "min": 0,
    "size": "Kolonie",
    "temp": "24-26°C",
    "flow": "hoch",
    "light": "hoch",
    "food": "Licht/Partikel",
    "agg": "⭐⭐⭐",
    "reef": "Bedingt",
    "form": "Kolonie",
    "note": "Variante",
    "img": "assets/img/coral.png"
  },
  {
    "name": "Montipora digitata 15 (Montipora)",
    "type": "coral",
    "min": 0,
    "size": "Kolonie",
    "temp": "24-26°C",
    "flow": "mittel-hoch",
    "light": "hoch",
    "food": "Licht/Partikel",
    "agg": "⭐⭐",
    "reef": "Bedingt",
    "form": "Kolonie",
    "note": "Variante",
    "img": "assets/img/coral.png"
  },
  {
    "name": "Zoanthus spp. 16 (Zoanthus)",
    "type": "coral",
    "min": 0,
    "size": "Kolonie",
    "temp": "24-26°C",
    "flow": "mittel",
    "light": "mittel",
    "food": "Licht/Partikel",
    "agg": "⭐",
    "reef": "Ja",
    "form": "Kolonie",
    "note": "Variante",
    "img": "assets/img/coral.png"
  },
  {
    "name": "Xenia spp. 17 (Xenia)",
    "type": "coral",
    "min": 0,
    "size": "Kolonie",
    "temp": "24-26°C",
    "flow": "niedrig",
    "light": "mittel",
    "food": "Licht/Partikel",
    "agg": "⭐",
    "reef": "Ja",
    "form": "Kolonie",
    "note": "Variante",
    "img": "assets/img/coral.png"
  },
  {
    "name": "Sarcophyton 18 (Lederkoralle)",
    "type": "coral",
    "min": 0,
    "size": "Kolonie",
    "temp": "24-26°C",
    "flow": "mittel",
    "light": "mittel",
    "food": "Licht/Partikel",
    "agg": "⭐⭐",
    "reef": "Ja",
    "form": "Kolonie",
    "note": "Variante",
    "img": "assets/img/coral.png"
  },
  {
    "name": "Ricordea florida 19 (Ricordea)",
    "type": "coral",
    "min": 0,
    "size": "Kolonie",
    "temp": "24-26°C",
    "flow": "niedrig",
    "light": "mittel",
    "food": "Licht/Partikel",
    "agg": "⭐",
    "reef": "Ja",
    "form": "Kolonie",
    "note": "Variante",
    "img": "assets/img/coral.png"
  },
  {
    "name": "Euphyllia glabrescens 20 (Torch)",
    "type": "coral",
    "min": 0,
    "size": "Kolonie",
    "temp": "24-26°C",
    "flow": "mittel",
    "light": "mittel",
    "food": "Licht/Partikel",
    "agg": "⭐⭐",
    "reef": "Ja",
    "form": "Kolonie",
    "note": "Variante",
    "img": "assets/img/coral.png"
  },
  {
    "name": "Acanthastrea spp. 21 (Acan)",
    "type": "coral",
    "min": 0,
    "size": "Kolonie",
    "temp": "24-26°C",
    "flow": "niedrig",
    "light": "niedrig",
    "food": "Licht/Partikel",
    "agg": "⭐",
    "reef": "Ja",
    "form": "Kolonie",
    "note": "Variante",
    "img": "assets/img/coral.png"
  },
  {
    "name": "Acropora spp. 22 (Acropora)",
    "type": "coral",
    "min": 0,
    "size": "Kolonie",
    "temp": "24-26°C",
    "flow": "hoch",
    "light": "hoch",
    "food": "Licht/Partikel",
    "agg": "⭐⭐⭐",
    "reef": "Bedingt",
    "form": "Kolonie",
    "note": "Variante",
    "img": "assets/img/coral.png"
  },
  {
    "name": "Montipora digitata 23 (Montipora)",
    "type": "coral",
    "min": 0,
    "size": "Kolonie",
    "temp": "24-26°C",
    "flow": "mittel-hoch",
    "light": "hoch",
    "food": "Licht/Partikel",
    "agg": "⭐⭐",
    "reef": "Bedingt",
    "form": "Kolonie",
    "note": "Variante",
    "img": "assets/img/coral.png"
  },
  {
    "name": "Zoanthus spp. 24 (Zoanthus)",
    "type": "coral",
    "min": 0,
    "size": "Kolonie",
    "temp": "24-26°C",
    "flow": "mittel",
    "light": "mittel",
    "food": "Licht/Partikel",
    "agg": "⭐",
    "reef": "Ja",
    "form": "Kolonie",
    "note": "Variante",
    "img": "assets/img/coral.png"
  }
];